// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final_project_final_project_group_9.Data;

#nullable disable

namespace final_project_final_project_group_9.Migrations
{
    [DbContext(typeof(TVShowsContext))]
    [Migration("20241206183826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("final_project_final_project_group_9.Models.TVShow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumSeasons")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TVShows");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Genre = "Drama",
                            NumSeasons = 7,
                            ReleaseDate = new DateOnly(2008, 1, 8),
                            ShowName = "Breaking bad"
                        },
                        new
                        {
                            ID = 2,
                            Genre = "Comedy",
                            NumSeasons = 20,
                            ReleaseDate = new DateOnly(1980, 7, 20),
                            ShowName = "Doremon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
