// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final_project_final_project_group_9.Data;

#nullable disable

namespace final_project_final_project_group_9.Migrations.TeamMembers
{
    [DbContext(typeof(TeamMembersContext))]
    [Migration("20241206182908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("final_project_final_project_group_9.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2004, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information system",
                            FullName = "Ying Orr",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2001, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT software development",
                            FullName = "Pranish Adhikari",
                            YearInProgram = "sophomore"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(2004, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT software development",
                            FullName = "Denis Kalala ",
                            YearInProgram = "Sophomore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
